version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - echo "******** Uploading to S3 ********"
      - aws s3 sync target/ s3://codebuildbokupnaMULE
artifacts:
  files:
    - target/testMaven-1.0-SNAPSHOT.jar